name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@309f3bb2d02cbd27732fea2e72121dbd9706e987 # v1.9.1
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
