name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@27b4d9664c93c311eb57d787a056a90b49c7a8f9 # v1.11.10
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
