name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@53eda0dc533761c17be282658e8ed6fdbb1d9221 # v1.3.0
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
