name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/.github/.github/workflows/dotnet-library-publish.yaml@main
    secrets: inherit
