name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@3a194c159b1086182818ddbbd5a4c177c785cbb7 # v1.11.11
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
