name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@367b3fd01c231fc685afb24ea9a8a04182780dad # v1.11.21
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
