name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@061ae5bdafe6d03d4930c2bd359e4c3256248dc8 # v1.11.19
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
