name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@95298ca496e9a955415673a0fdf13e20d1f17bb8 # v1.11.6
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
