name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/cd-dotnet-library-publish.yaml@fbfd051d3029c9f8d2bb64a87a329c824241fc36 # v1.1.6
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
