name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@061ae5bdafe6d03d4930c2bd359e4c3256248dc8 # v1.11.19
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
