name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@95298ca496e9a955415673a0fdf13e20d1f17bb8 # v1.11.6
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
