name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@53eda0dc533761c17be282658e8ed6fdbb1d9221 # v1.3.0
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
