name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@e6d4863dbd3dbed78bbb321accb35c7012452bbd # v1.11.15
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
