name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@27b4d9664c93c311eb57d787a056a90b49c7a8f9 # v1.11.10
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
