name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@3a194c159b1086182818ddbbd5a4c177c785cbb7 # v1.11.11
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
