name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@309f3bb2d02cbd27732fea2e72121dbd9706e987 # v1.9.1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
