name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@d2a8a765b231b56fe1449a22a2b219f5d8cc398b # v1.15.1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
