name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@367b3fd01c231fc685afb24ea9a8a04182780dad # v1.11.21
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
