name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/ci-dotnet-test.yaml@accc9b52ba37468aedf9cf1b2a3244684000d730 # v1.11.22
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
